spring.application.name=educonnect-platform

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://db.kfwibxrtdplrbyzuzjdw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings (optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
